export const CATEGORIES: Record<string, string[]> = {
  Objects: [
    'Airplane',
    'Anchor',
    'Backpack',
    'Balloon',
    'Banana',
    'Battery',
    'Bed',
    'Bell',
    'Bicycle',
    'Blanket',
    'Book',
    'Boomerang',
    'Bottle',
    'Broom',
    'Bucket',
    'Camera',
    'Candle',
    'Canoe',
    'Car',
    'Chair',
    'Clock',
    'Compass',
    'Couch',
    'Doctor',
    'Door',
    'Drum',
    'Envelope',
    'Eyeglasses',
    'Fire hydrant',
    'Flag',
    'Flashlight',
    'Football',
    'Glasses',
    'Globe',
    'Guitar',
    'Hammer',
    'Hat',
    'Headphones',
    'Helmet',
    'Hourglass',
    'Key',
    'Kite',
    'Ladder',
    'Lamp',
    'Lantern',
    'Mailbox',
    'Megaphone',
    'Microphone',
    'Mirror',
    'Necklace',
    'Newspaper',
    'Paintbrush',
    'Paperclip',
    'Phone',
    'Piano',
    'Pillow',
    'Pocket watch',
    'Present',
    'Radio',
    'Ring',
    'Robot',
    'Rocket',
    'Sailboat',
    'Scissors',
    'Ship',
    'Shoe',
    'Skateboard',
    'Sled',
    'Snowflake',
    'Soap',
    'Sock',
    'Spoon',
    'Stamp',
    'Suitcase',
    'Sunglasses',
    'Telescope',
    'Tent',
    'Toothbrush',
    'Tractor',
    'Train',
    'Treasure chest',
    'Trophy',
    'Umbrella',
    'Vacuum',
    'Violin',
    'Wagon',
    'Wallet',
    'Wheelbarrow',
    'Window',
    'Wrench',
    'Yo-yo',
  ],
  Food: [
    'Apple',
    'Avocado',
    'Bacon',
    'Bagel',
    'Banana split',
    'Blueberry',
    'Bread',
    'Burger',
    'Burrito',
    'Cake',
    'Candy cane',
    'Carrot',
    'Cheese',
    'Cherry',
    'Chicken nugget',
    'Chili pepper',
    'Chocolate',
    'Cinnamon roll',
    'Coconut',
    'Coffee',
    'Cookie',
    'Corn',
    'Croissant',
    'Cupcake',
    'Donut',
    'Egg',
    'French fries',
    'Grapes',
    'Hamburger',
    'Honey',
    'Hot dog',
    'Ice cream',
    'Jelly',
    'Lemon',
    'Lollipop',
    'Macaroni',
    'Mango',
    'Maple syrup',
    'Milk',
    'Muffin',
    'Mushroom',
    'Nachos',
    'Noodles',
    'Orange',
    'Pancakes',
    'Peanut',
    'Pear',
    'Pickle',
    'Pie',
    'Pineapple',
    'Pizza',
    'Popcorn',
    'Pretzel',
    'Pumpkin',
    'Sandwich',
    'Spaghetti',
    'Strawberry',
    'Sushi',
    'Taco',
    'Toast',
    'Tomato',
    'Waffle',
    'Watermelon',
  ],
  Animals: [
    'Alligator',
    'Ant',
    'Bat',
    'Bear',
    'Bee',
    'Butterfly',
    'Camel',
    'Cat',
    'Caterpillar',
    'Chicken',
    'Crab',
    'Crocodile',
    'Deer',
    'Dinosaur',
    'Dog',
    'Dolphin',
    'Duck',
    'Eagle',
    'Elephant',
    'Flamingo',
    'Fox',
    'Frog',
    'Giraffe',
    'Goat',
    'Gorilla',
    'Hedgehog',
    'Hippo',
    'Horse',
    'Hummingbird',
    'Jellyfish',
    'Kangaroo',
    'Koala',
    'Ladybug',
    'Lion',
    'Lizard',
    'Lobster',
    'Monkey',
    'Moose',
    'Mouse',
    'Octopus',
    'Ostrich',
    'Otter',
    'Owl',
    'Panda',
    'Parrot',
    'Peacock',
    'Penguin',
    'Pig',
    'Polar bear',
    'Rabbit',
    'Raccoon',
    'Rhino',
    'Rooster',
    'Seal',
    'Shark',
    'Sheep',
    'Skunk',
    'Sloth',
    'Snail',
    'Snake',
    'Spider',
    'Squirrel',
    'Starfish',
    'Swan',
    'Tiger',
    'Toad',
    'Turtle',
    'Walrus',
    'Whale',
    'Wolf',
    'Zebra',
  ],
  Places: [
    'Airport',
    'Amusement park',
    'Arctic',
    'Attic',
    'Bakery',
    'Barn',
    'Beach',
    'Bridge',
    'Cabin',
    'Cafe',
    'Campground',
    'Carnival',
    'Castle',
    'Cave',
    'Church',
    'Circus',
    'City',
    'Classroom',
    'Cliff',
    'Desert',
    'Dock',
    'Farm',
    'Ferris wheel',
    'Fire station',
    'Forest',
    'Fountain',
    'Garage',
    'Garden',
    'Gas station',
    'Graveyard',
    'Harbor',
    'Haunted house',
    'Hospital',
    'Igloo',
    'Island',
    'Jungle',
    'Kitchen',
    'Lighthouse',
    'Library',
    'Moon',
    'Mountain',
    'Museum',
    'Ocean',
    'Office',
    'Park',
    'Playground',
    'Pond',
    'Pyramid',
    'Rainforest',
    'Ranch',
    'Roof',
    'School',
    'Skyscraper',
    'Stadium',
    'Subway',
    'Swimming pool',
    'Theater',
    'Treehouse',
    'Volcano',
    'Waterfall',
    'Windmill',
    'Zoo',
  ],
  Actions: [
    'Backpacking',
    'Baking bread',
    'Brushing teeth',
    'Building a campfire',
    'Catching a butterfly',
    'Climbing a tree',
    'Dancing',
    'Directing a symphony',
    'Directing traffic',
    'Doing the dishes',
    'Driving a racecar',
    'Eating spaghetti',
    'Feeding ducks',
    'Fishing',
    'Flying a kite',
    'Getting a haircut',
    'Hiking',
    'Hula hooping',
    'Ice skating',
    'Ironing clothes',
    'Juggling',
    'Jumping rope',
    'Kayaking',
    'Making a snowman',
    'Mowing the lawn',
    'Opening a present',
    'Painting a canvas',
    'Playing basketball',
    'Playing hopscotch',
    'Playing the drums',
    'Popping a balloon',
    'Raking leaves',
    'Riding a roller coaster',
    'Rock climbing',
    'Rowing a boat',
    'Scuba diving',
    'Sewing',
    'Shoveling snow',
    'Skateboarding',
    'Skiing downhill',
    'Sleeping',
    'Surfing',
    'Swinging',
    'Taking a selfie',
    'Throwing a paper airplane',
    'Walking a dog',
    'Walking a tightrope',
    'Walking on ice',
    'Washing a car',
    'Watering plants',
    'Whistling',
    'Yawning',
  ],
  Movies: [
    'Alice in Wonderland',
    'Aladdin',
    'Batman',
    'Beauty and the Beast',
    'Cinderella',
    'E.T.',
    'Finding Nemo',
    'Frozen',
    'Ghostbusters',
    'Harry Potter',
    'Home Alone',
    'Indiana Jones',
    'Iron Man',
    'Jaws',
    'Jurassic Park',
    'King Kong',
    'Mario',
    'Mary Poppins',
    'Moana',
    'Peter Pan',
    'Pikachu',
    'Pinocchio',
    'Scooby-Doo',
    'Shrek',
    'Sleeping Beauty',
    'Snow White',
    'Spider-Man',
    'SpongeBob SquarePants',
    'Star Wars',
    'Superman',
    'Tarzan',
    'The Grinch',
    'The Jungle Book',
    'The Lion King',
    'The Little Mermaid',
    'The Wizard of Oz',
    'Titanic',
    'Toy Story',
    'Up',
    'Wall-E',
    'Willy Wonka',
  ],
  Idioms: [
    'A drop in the bucket',
    'Barking up the wrong tree',
    'Beat around the bush',
    'Bite the bullet',
    'Blessing in disguise',
    'Break the ice',
    'Burning the midnight oil',
    'Butterflies in your stomach',
    'Cold feet',
    'Cool as a cucumber',
    'Cry over spilled milk',
    'Cry wolf',
    'Curiosity killed the cat',
    'Cutting corners',
    "Don't count your chickens",
    'Down to earth',
    'Drive someone crazy',
    'Easier said than done',
    'Elephant in the room',
    'Fish out of water',
    'Go the extra mile',
    'Head over heels',
    'Hit the hay',
    'Hit the nail on the head',
    'Hold your horses',
    'In hot water',
    'Jumping to conclusions',
    'Kick the bucket',
    'Let the cat out of the bag',
    'On cloud nine',
    'Once in a blue moon',
    'Out of the blue',
    'Over the moon',
    'Piece of cake',
    "Pulling someone's leg",
    'Raining cats and dogs',
    'Saved by the bell',
    'Spill the beans',
    'The ball is in your court',
    'The early bird',
    'Throw in the towel',
    'Under the weather',
    'When pigs fly',
    'Wild goose chase',
  ],
  Silly: [
    'Alien',
    'Bigfoot',
    'Cowboy',
    'Dragon',
    'Fairy',
    'Fire',
    'Genie',
    'Ghost',
    'Giant',
    'Knight',
    'Leprechaun',
    'Mermaid',
    'Monster',
    'Mummy',
    'Ninja',
    'Pirate',
    'Princess',
    'Robot dog',
    'Santa',
    'Snowman',
    'Sorcerer',
    'Superhero',
    'Troll',
    'Unicorn',
    'Vampire',
    'Werewolf',
    'Witch',
    'Wizard',
    'Yeti',
    'Zombie',
  ],
}

const STOPWORDS = new Set([
  'a',
  'an',
  'the',
  'in',
  'on',
  'at',
  'with',
  'of',
  'and',
  'to',
  'for',
  'from',
  'into',
  'by',
  'is',
  'it',
  'your',
  'you',
  'someone',
  'someones',
  'dont',
  'not',
  'up',
  'out',
  'over',
  'down',
  'off',
  'about',
])

export type CategoryOptions = {
  category: string
  prompts: string[]
}

function shuffle<T>(items: T[]) {
  const next = [...items]
  for (let i = next.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1))
    const a = next[i]
    const b = next[j]
    if (a === undefined || b === undefined) continue
    next[i] = b
    next[j] = a
  }
  return next
}

export function dealPromptOptions(): CategoryOptions[] {
  const names = shuffle(Object.keys(CATEGORIES)).slice(0, 3)
  return names.map((category) => {
    const list = CATEGORIES[category] ?? []
    return {
      category,
      prompts: shuffle(list).slice(0, 3),
    }
  })
}

export function normalizeAnswer(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9 ]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}

function stem(word: string) {
  if (word.length >= 6 && word.endsWith('ing')) {
    return word.slice(0, -3)
  }
  if (word.length >= 5 && word.endsWith('ed')) {
    return word.slice(0, -2)
  }
  if (word.length > 3 && word.endsWith('s') && !word.endsWith('ss')) {
    return word.slice(0, -1)
  }
  return word
}

export function contentWords(value: string) {
  return normalizeAnswer(value)
    .split(' ')
    .filter((word) => word.length >= 2 && !STOPWORDS.has(word))
    .map(stem)
}

export function answersMatch(guess: string, prompt: string) {
  const guessNorm = normalizeAnswer(guess)
  const promptNorm = normalizeAnswer(prompt)
  if (!guessNorm || !promptNorm) return false
  if (guessNorm === promptNorm) return true

  const guessWords = contentWords(guess)
  const promptWords = contentWords(prompt)
  if (guessWords.length === 0 || promptWords.length === 0) return false

  const guessSet = new Set(guessWords)
  if (promptWords.every((word) => guessSet.has(word))) return true

  if (promptWords.length >= 4) {
    const longest = [...promptWords].sort((a, b) => b.length - a.length)[0]
    const hits = promptWords.filter((word) => guessSet.has(word))
    return Boolean(longest && guessSet.has(longest) && hits.length >= promptWords.length - 1)
  }
  return false
}

export function maskSecret(value: string) {
  return value.replace(/[A-Za-z0-9]/g, '*')
}

export function optionExists(options: CategoryOptions[], category: string, prompt: string) {
  const group = options.find((item) => item.category === category)
  return Boolean(group?.prompts.includes(prompt))
}
